HotelWebApp/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using HotelWebApp.Models;
using Microsoft.EntityFrameworkCore;
using HotelWebApp.ViewModels;
using ApplicationServices.DTOs;
using ApplicationServices.Services;
using FluentValidation;
using FluentValidation.AspNetCore;

namespace HotelWebApp.Controllers
{
    public class RoomsController : Controller
    {
        private readonly HotelServices sql;
        public OperationsModel operations = new OperationsModel();
        private readonly IValidator<RoomsInfoViewModel> validator;

        public RoomsController(HotelServices _sql, IValidator<RoomsInfoViewModel> _validator)
        {
            sql = _sql;
            validator = _validator;
         }

        // Rooms index page, displays a list of rooms with some basic info
        public async Task<IActionResult> Index()
        {
            // Using a list here because there are lists of reviews and their counts + ratings attached to each unique room
            List<RoomsIndexViewModel> roomReviewViewModel = new List<RoomsIndexViewModel>();

            var roomTypes = await sql.GetAllRoomTypes();

            // Must populate RoomsIndexViewModel with a room + all the reviews for that room

            foreach (var roomType in roomTypes)
            {
                var reviews = await sql.GetReviewsByRoomTypeId(roomType.Id);

                roomReviewViewModel.Add(new RoomsIndexViewModel
                {
                    RoomType = roomType,
                    ReviewCount = reviews.Count(),
                    Rating = operations.RoundRatings(reviews, roomType.Id) // Rounds the ratings
                });
            }
       
            return View(roomReviewViewModel);
        }


        public async Task<IActionResult> Info(RoomsInfoViewModel obj)
        {
            obj.RoomType = await sql.GetRoomTypeById(obj.RoomTypeId);
            obj.Reviews = await sql.GetReviewsByRoomTypeId(obj.RoomTypeId);

            return View(obj);
        }

        // Apparently my POST looks like what a GET should look like
        // and no url tempalte in HttpPost?
        // Making the signature invalid?

        [HttpPost]
        public async Task<IActionResult> Info(int roomTypeId)
        {
            RoomsInfoViewModel viewModel = new RoomsInfoViewModel
            {
                RoomType = await sql.GetRoomTypeById(roomTypeId),
                Reviews = await sql.GetReviewsByRoomTypeId(roomTypeId)
            };

            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> PostReview(RoomsInfoViewModel obj)
        {
            var result = await validator.ValidateAsync(obj);
            result.AddToModelState(this.ModelState);

            if (ModelState.IsValid) // I.e. if the user has posted a description and rating and within the constraints
            {
                await sql.CreateReview(obj.Description, obj.Rating, obj.UserEmail, obj.RoomTypeId);

                return RedirectToAction("Info", obj);
            }

            // Need to get the reviews again for page refresh, where the updated reviews are posted.
            obj.Reviews = await sql.GetReviewsByRoomTypeId(obj.RoomTypeId);
            obj.RoomType = await sql.GetRoomTypeById(obj.RoomTypeId);

            return View("Info", obj);
        }
    }
}

HotelWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelWebApp</title>
    <link rel="stylesheet" href="~/css/flatlyTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HotelWebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <script src="https://kit.fontawesome.com/1ff7cfb9b1.js" crossorigin="anonymous"></script>

    @*doesn't work*@

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kenan's Hotel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a>
                        </li>
                        @{
                            if(User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                                </li>
                            }  
                        }   
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HotelWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>