HotelWebApp/Controllers/CMSControllers/RoomTypeController.cs
using ApplicationServices.Services;
using FluentValidation;
using FluentValidation.AspNetCore;
using HotelWebApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HotelWebApp.Controllers.CMSControllers
{
    public class RoomTypeController : Controller
    {
        private readonly AdminServices sqlCrud;
        private readonly HotelServices sql;
        private readonly IValidator<CMSRoomTypeCreateViewModel> createValidator;
        private readonly IValidator<CMSRoomTypeEditViewModel> editValidator;

        public RoomTypeController(AdminServices _sqlCrud, HotelServices _sql, 
            IValidator<CMSRoomTypeEditViewModel> _editValidator,
            IValidator<CMSRoomTypeCreateViewModel> _createValidator)
        {
            sqlCrud = _sqlCrud;
            sql = _sql;
            createValidator = _createValidator;
            editValidator = _editValidator;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            CMSRoomTypeCreateViewModel viewModel = new CMSRoomTypeCreateViewModel
            {
                Amenities = (await sql.GetAmenities()).Select(x => x.Name).ToList() // Can I do queries here?
            };


            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(CMSRoomTypeCreateViewModel viewModel)
        {
            var result = createValidator.Validate(viewModel);
            result.AddToModelState(this.ModelState);

            if (ModelState.IsValid)
            {
                await sqlCrud.CreateRoomType(viewModel.Title, viewModel.Price, 
                    viewModel.Description, viewModel.ImgUrl, viewModel.Size, 
                    viewModel.Amenities);

                return RedirectToAction("Index", "Admin");
            }
            
            // Otherwise I get uninstantiated object error
            CMSRoomTypeCreateViewModel output = new CMSRoomTypeCreateViewModel
            {
                Amenities = (await sql.GetAmenities()).Select(x => x.Name).ToList() 
            };

            return View("Create", output);
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete()
        {
            CMSRoomTypeCreateViewModel viewModel = new CMSRoomTypeCreateViewModel
            {
                RoomTypes = await sql.GetAllRoomTypes()
            };

            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            await sqlCrud.DeleteRoomType(id);

            return RedirectToAction("Delete");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit()
        {
            CMSRoomTypeEditViewModel viewModel = new CMSRoomTypeEditViewModel
            {
                RoomTypes = await sql.GetAllRoomTypes(),
                Amenities = (await sql.GetAmenities()).Select(x => x.Name).ToList(),
            };

            return View(viewModel);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(CMSRoomTypeEditViewModel obj)
        {
            // Validate to make sure no null values
           

            if(ModelState.IsValid)
            {
                for (int i = 0; i < obj.Ids.Count(); i++)
                {
                    // Cheap but quick solution. In the view, I add the iterator to the beginning of every amenity
                    // Here I store the amenity associated with the right roomtype and then remove the letter.
                   
                    string digit = Convert.ToString(i);
                    var amenities = obj.Amenities.Where(x => x.Contains(digit)).Select(x => x.Substring(1)).ToList();

                    await sqlCrud.EditRoomType(obj.Titles[i], obj.Prices[i], obj.Descriptions[i], obj.ImgUrls[i], obj.Sizes[i], amenities, obj.Ids[i]);
                }
                    
            }
            

            return RedirectToAction("Edit");
        }

    }
}

HotelWebApp/Views/RoomType/Create.cshtml
@using HotelWebApp.ViewModels
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@using HotelWebApp.ViewModels

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CMSRoomTypeCreateViewModel




<form method="post" asp-controller="RoomType" asp-action="Create">
             <div>
            <label asp-for="Title"></label>
            <input asp-for="Title" class="col-xs-4"/>
            <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <br />
                <div>
            <label asp-for="Price"></label>
            <input asp-for="Price" class="col-xs-4" />
            <span asp-validation-for="Price" class="text-danger"></span>
             </div>
             <div>
            <label asp-for="Description"></label>
            <input asp-for="Description" class="col-xs-4" />
            <span asp-validation-for="Description" class="text-danger"></span>
             </div>
             <div>
            <label asp-for="ImgUrl"></label>
            <input asp-for="ImgUrl" class="col-xs-4" />
            <span asp-validation-for="ImgUrl" class="text-danger"></span>
             </div>
             <div>
            <label asp-for="Size"></label>
            <input asp-for="Size" class="col-xs-4" />
            <span asp-validation-for="Size" class="text-danger"></span>
             </div>
             <div>
                @{
            foreach(var amenity in Model.Amenities)
                {
                <input type="checkbox" name="Amenities" value="@amenity">
                <label for="@amenity">@amenity</label>       
                }
                }
             </div>
             <button type="submit" class="btn btn-info">Create</button>
        </form>

HotelWebApp/Views/RoomType/Delete.cshtml
@using HotelWebApp.ViewModels
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CMSRoomTypeCreateViewModel

@{
    foreach(var item in Model.RoomTypes)
    {
        <form method="post" asp-controller="RoomType" asp-action="Delete">
        <p>@item.Title</p>
        <input type="hidden" value="@item.Id" name="id">
        <input type="submit" value="Delete">
        </form>
    }
}

HotelWebApp/Views/RoomType/Edit.cshtml
@using HotelWebApp.ViewModels;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model CMSRoomTypeEditViewModel
<form method="post" asp-controller="RoomType" asp-action="Edit">
    <div asp-validation-summary="All" class="text-danger">
    </div>
@{
    for(int i = 0; i < @Model.RoomTypes.Count(); i++)
    {
        <div>
        <label asp-for="Titles"></label>
        <input asp-for="Titles" value="@Model.RoomTypes[i].Title" class="col-xs-4"/>
        <span asp-validation-for="Titles[i]" class="text-danger"></span>
        </div>
        <div>
        <label asp-for="Descriptions"></label>
        <input asp-for="Descriptions" value="@Model.RoomTypes[i].Description" class="col-xs-4"/>
        <span asp-validation-for="Descriptions[i]" class="text-danger"></span>
        </div>
         <div>
        <label asp-for="Prices"></label>
        <input asp-for="Prices" value="@Model.RoomTypes[i].Price" class="col-xs-4"/>
        <span asp-validation-for="Prices[i]" class="text-danger"></span>
        </div>
         <div>
        <label asp-for="ImgUrls"></label>
        <input asp-for="ImgUrls" value="@Model.RoomTypes[i].ImgUrl" class="col-xs-4"/>
        <span asp-validation-for="ImgUrls[i]" class="text-danger"></span>
        </div>
        <div>
        <label asp-for="Sizes"></label>
        <input asp-for="Sizes" value="@Model.RoomTypes[i].Size" class="col-xs-4"/>
        <span asp-validation-for="Sizes[i]" class="text-danger"></span>
        </div>
        <div>
        @{
            foreach(var amenity in Model.Amenities)
                {
                 <input type="checkbox" name="Amenities" value="@i@amenity">
                 <label for="@amenity">@amenity</label>       
                }
                }
        </div>        
        <input asp-for="Ids" value="@Model.RoomTypes[i].Id" type="hidden">
        <br />
    }
}
<input type="submit" value="Edit">
        </form>