HotelWebApp/Controllers/CMSControllers/RoomController.cs
using ApplicationServices.Services;
using HotelWebApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HotelWebApp.Controllers.CMSControllers
{
    public class RoomController : Controller
    {
        private readonly HotelServices sql;
        private readonly AdminServices sqlCrud;
        public RoomController(HotelServices _sql, AdminServices _sqlCrud)
        {
            sql = _sql;
            sqlCrud = _sqlCrud;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            // Get All room numbers to exlcude async
            var roomsToExclude = (await sql.GetAllRooms()).Select(x => x.RoomNumber).ToList(); 

            CMSRoomViewModel viewModel = new CMSRoomViewModel()
            {
                RoomTypes = (await sql.GetAllRoomTypes()).Select(x => x.Title).ToList(),
                //AvailableRoomNumbers between 1-100
                RoomNumbers = Enumerable.Range(1, 100).Except(roomsToExclude).ToList()
            };

            return View(viewModel);
        }
        // Refactor this controller, using fluent validation

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(CMSRoomViewModel viewModel) 
        {
            var roomsToExclude = (await sql.GetAllRooms()).Select(x => x.RoomNumber).ToList();

            // Makes sure they cannot input duplicates via the inspector
            if (roomsToExclude.Contains(viewModel.RoomNumber))
            {
                ModelState.AddModelError("", "Room Number is not available");
            }
            // If the room type selected does not exist 
            if (!(await sql.GetAllRoomTypes()).Select(x => x.Title).Contains(viewModel.RoomType)) 
            {
                ModelState.AddModelError("", "Room type is not valid");
            }

            if(ModelState.IsValid)
            {
                await sqlCrud.CreateRoom(viewModel.RoomType, viewModel.RoomNumber);

                return RedirectToAction("Index", "Admin");
            }


            CMSRoomViewModel output = new CMSRoomViewModel()
            {
                RoomTypes = (await sql.GetAllRoomTypes()).Select(x => x.Title).ToList(),
                RoomNumbers = Enumerable.Range(1, 100).Except(roomsToExclude).ToList()
            };

            return View("Create", output);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete()
        {
            CMSRoomViewModel viewModel = new CMSRoomViewModel
            {
                RoomNumbers = (await sql.GetAllRooms()).Select(x => x.RoomNumber).ToList()
            };

            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int roomNumber)
        {
            await sqlCrud.DeleteRoom(roomNumber);

            return RedirectToAction("Delete");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit()
        {
            CMSRoomViewModel viewModel = new CMSRoomViewModel
            {
                RoomNumbers = (await sql.GetAllRooms()).Select(x => x.RoomNumber).ToList(),
                RoomTypes = (await sql.GetAllRoomTypes()).Select(x => x.Title).ToList()
            };

            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            return RedirectToAction("Delete");
        }

    }
}

HotelWebApp/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using HotelWebApp.Models;
using Microsoft.EntityFrameworkCore;
using HotelWebApp.ViewModels;
using ApplicationServices.DTOs;
using ApplicationServices.Services;
using FluentValidation;
using FluentValidation.AspNetCore;

namespace HotelWebApp.Controllers
{
    public class RoomsController : Controller
    {
        private readonly HotelServices sql;
        public OperationsModel operations = new OperationsModel();
        private readonly IValidator<RoomsInfoViewModel> validator;

        public RoomsController(HotelServices _sql, IValidator<RoomsInfoViewModel> _validator)
        {
            sql = _sql;
            validator = _validator;
         }

        // Rooms index page, displays a list of rooms with some basic info
        public async Task<IActionResult> Index()
        {
            // Using a list here because there are lists of reviews and their counts + ratings attached to each unique room
            List<RoomsIndexViewModel> roomReviewViewModel = new List<RoomsIndexViewModel>();

            var roomTypes = await sql.GetAllRoomTypes();

            // Must populate RoomsIndexViewModel with a room + all the reviews for that room

            foreach (var roomType in roomTypes)
            {
                var reviews = await sql.GetReviewsByRoomTypeId(roomType.Id);

                roomReviewViewModel.Add(new RoomsIndexViewModel
                {
                    RoomType = roomType,
                    ReviewCount = reviews.Count(),
                    Rating = operations.RoundRatings(reviews, roomType.Id) // Rounds the ratings
                });
            }
       
            return View(roomReviewViewModel);
        }


        public async Task<IActionResult> Info(RoomsInfoViewModel obj)
        {
            obj.RoomType = await sql.GetRoomTypeById(obj.RoomTypeId);
            obj.Reviews = await sql.GetReviewsByRoomTypeId(obj.RoomTypeId);

            return View(obj);
        }

        // Apparently my POST looks like what a GET should look like
        // and no url tempalte in HttpPost?
        // Making the signature invalid?

        [HttpPost]
        public async Task<IActionResult> Info(int roomTypeId)
        {
            RoomsInfoViewModel viewModel = new RoomsInfoViewModel
            {
                RoomType = await sql.GetRoomTypeById(roomTypeId),
                Reviews = await sql.GetReviewsByRoomTypeId(roomTypeId)
            };

            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> PostReview(RoomsInfoViewModel obj)
        {
            var result = await validator.ValidateAsync(obj);
            result.AddToModelState(this.ModelState);

            if (ModelState.IsValid) // I.e. if the user has posted a description and rating and within the constraints
            {
                await sql.CreateReview(obj.Description, obj.Rating, obj.UserEmail, obj.RoomTypeId);

                return RedirectToAction("Info", obj);
            }

            // Need to get the reviews again for page refresh, where the updated reviews are posted.
            obj.Reviews = await sql.GetReviewsByRoomTypeId(obj.RoomTypeId);
            obj.RoomType = await sql.GetRoomTypeById(obj.RoomTypeId);

            return View("Info", obj);
        }
    }
}

HotelWebApp/Views/Room/Create.cshtml
@using HotelWebApp.ViewModels;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CMSRoomViewModel


<form method="post" asp-controller="Room" asp-action="Create">
            <div asp-validation-summary="All"></div>
            <div>
            <select asp-for="RoomType" 
                asp-items="@(new SelectList(Model.RoomTypes))">
                <option>Please select a room type</option>
            </select>
            </div>
            <div>
              <select asp-for="RoomNumber" 
                asp-items="@(new SelectList(Model.RoomNumbers))">
                <option>Please select a room number</option>
            </select>
            </div>
             <button type="submit" class="btn btn-info">Create</button>
        </form>

HotelWebApp/Views/Room/Delete.cshtml
@using HotelWebApp.ViewModels
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model CMSRoomViewModel

@{
    foreach(var item in Model.RoomNumbers)
    {
        <form method="post" asp-controller="Room" asp-action="Delete">
        <p>Room Number: @item</p>
        <input type="hidden" value="@item" name="roomNumber">
        <input type="submit" value="Delete">
        </form>
    }
}

HotelWebApp/Views/Room/Edit.cshtml
@using HotelWebApp.ViewModels;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model CMSRoomViewModel

@{
    foreach(var item in Model.RoomNumbers)
    {
        <form method="post" asp-controller="Room" asp-action="Edit">
       <div>
       <p>Room Number: @item</p>
              <select asp-for="RoomType" 
                asp-items="@(new SelectList(Model.RoomTypes))">
                <option>Select a room type</option>
            </select>
        </div>
        <input type="hidden" value="" name="id">
        <input type="submit" value="Edit">
        </form>
        <br />
    }
}